server:
  port: 0

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
          inventory-service:
            connectTimeout: 2000
            readTimeout: 3000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/order_db
    username: ${POSTGRES_USER:dbuser}
    password: ${POSTGRES_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

logging:
  level:
    ru.yandex.practicum.order.client.InventoryClient: DEBUG
