server:
  port: 0

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
          inventory-service:
            connectTimeout: 2000
            readTimeout: 3000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/order_db
    username: ${POSTGRES_USER:dbuser}
    password: ${POSTGRES_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

logging:
  level:
    ru.yandex.practicum.order.client.InventoryClient: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
